services:
  postgres:
    image: postgres:16
    container_name: l0_database
    restart: always
    env_file: ".env"
    ports:
      - "${PGPORT}:${PGPORT}"
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -d $${PGDATABASE} -U $${PGUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  app:
    container_name: l0_app
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge


